### ISSUE TITLE
UI: 標題樣式

### ISSUE THREAD

**Issue by ChloeTsaiLin** [Digo19930701/PetPlatfrom#2]
@Cissto 
測試版本: SellerBase: 9/28 [12303b1] <- 是跟SellerSystem: 9/27 [19ff602] merge的
標題與部分版面有時候會吃到不同樣式

新增/編輯服務:
<img width="479" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/2ae2054e-7927-47b0-ba09-4b8a0964f4b9">
<img width="386" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/9b684d6c-3217-4c78-8539-ca734d629504">

訂單管理類:
(各類別訂單的標題目前還沒辦法跟著變 請見下圖**url與內容**)
<img width="517" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/208323c3-4340-40ab-88db-661e0da74ea0">
<img width="515" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/82982689-2d69-41d3-b1c8-07a10a5e4a65">
吃過帳務管理後
(只有帳務管理是標題在底板範圍內的)
<img width="517" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/434a3f93-8e12-40b3-972c-661164abc1d5">
重新整理後
(可以注意到訂單樣式跟日期底色等也不一樣)
<img width="516" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/447c289b-9570-4b65-b51b-8a8f5552a9c3">

數據中心:
run dev後按照順序點下來的樣式
<img width="518" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/d3cc346d-564f-4747-aa69-6b6ca18496d9">

吃過帳務管理後
(只有帳務管理是標題在底板範圍內的)
<img width="514" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/98eee9c3-f0df-47a0-b150-5897688d19b2">
重整後
<img width="516" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/0df04488-b825-4f74-8bc8-d1b254492fd2">

不同頁面大小不同的問題:
如下圖 "現有服務"明顯比"商家基本資料"大
<img width="540" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/2e734421-86fd-436a-9199-991b76b7ea18">
<img width="539" alt="image" src="https://github.com/Digo19930701/PetPlatfrom/assets/120118608/67df1151-895d-40b5-b4a3-3525284847d3">

**Comment by ghost** [comment]
Done
